sudo: true
language: node_js
node_js:
  - 12
# cache:
#   yarn: true
#   directories:
#     - node_modules
notifications:
  email:
    on_success: change
    on_failure: always
# before_install:
# - sudo apt-get install sshpass
install:
  - yarn
jobs:
  include:
    - stage: test
    - stage: build
    - stage: deploy

    - script:
        - yarn prettier --check
        - yarn tslint
        - yarn coverage
        - yarn coveralls
        - yarn build-all
        # - export SSHPASS=${SFTP_PASSWORD}
        # - sshpass -e sftp -oBatchMode=no -b batchfile.sftp ${SFTP_USER}@${SFTP_HOST}:poc
        # - curl --ftp-create-dirs -T dist/angular.js sftp://${SFTP_USER}:${SFTP_PASSWORD}@${SFTP_HOST}/poc/angular.js
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    all_branches: true
