sudo: true
language: node_js
node_js:
  - 12
# cache:
#   yarn: true
#   directories:
#     - node_modules
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
  - sudo apt-get install sshpass
install:
  # - yarn
  - ls -la
jobs:
  include:
    - script:
        - yarn prettier --check
        # - yarn coverage
        # - yarn coveralls
        # - yarn build-all
        - export SSHPASS=${SFTP_PASSWORD}
        - sshpass -e sftp -oBatchMode=no -b batchfile.sftp ${SFTP_USER}@${SFTP_HOST}:poc
