# sudo: true
language: node_js
node_js:
  - 'lts/*'
notifications:
  email:
    on_success: change
    on_failure: always
addons:
  chrome: stable
  apt:
    packages:
      - libgconf-2-4
# before_install:
#   - sudo apt-get install sshpass
# cache:
#   npm: false
#   directories:
#     - ~/.cache
#     - ./node_modules
# install:
#   - npm run reinstall
# - npm install --no-save
# - npm update --no-save
script:
  - npm outdated || true
  - prettier --check src/**/*.html src/**/*.js src/**/*.json src/**/*.jsx src/**/*.ts src/**/*.tsx src/**/*.vue
  - npm run coverage
  - npm run coveralls
  # - npm run e2e -- --headless
  - npx nightwatch -e selenium.chrome
  - npx nightwatch -e selenium.firefox
  - npm run build-all
  # - export SSHPASS=${SFTP_PASSWORD}
  # - sshpass -e sftp -oBatchMode=no -b batchfile.sftp ${SFTP_USER}@${SFTP_HOST}:poc
  # - curl --ftp-create-dirs -T dist/angular.js sftp://${SFTP_USER}:${SFTP_PASSWORD}@${SFTP_HOST}/poc/angular.js
# deploy:
#   skip_cleanup: true
#   provider: script
#   script: bash scripts/deploy.sh
#   on:
#     all_branches: true
# after_success:
#   - ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" ${SFTP_USER}@${SFTP_HOST}
#   - export SSHPASS=${SFTP_PASSWORD}
#   - sshpass -e sftp -oBatchMode=no -b scripts/batchfile.sftp ${SFTP_USER}@${SFTP_HOST}:poc
