dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - 12
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email:
    on_success: change
    on_failure: always
install:
  - yarn
jobs:
  include:
    - script:
        - yarn prettier --check
        - yarn coverage
        - yarn coveralls
        - yarn build-all
        - yarn serve inferno
