language: node_js
node_js:
  - 12
# cache:
#   yarn: true
#   directories:
#     - node_modules
notifications:
  email:
    on_success: change
    on_failure: always
install:
  - yarn
jobs:
  include:
    - script:
        - yarn prettier --check
        # - yarn coverage
        # - yarn coveralls
        # - yarn build-all
after_success:
  - echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
  - curl --ftp-create-dirs
    -T filename
    --key /tmp/sftp_rsa
    sftp://${SFTP_USER}:${SFTP_PASSWORD}@${SFTP_HOST}/poc/
