language: node_js
node_js:
  - 12
notifications:
  email:
    on_success: change
    on_failure: always
install:
  - npm run update
jobs:
  include:
  - script:
    - npm run test
    - npm run build-all
