language: node_js
node_js:
  - 12
# cache:
#   yarn: true
#   directories:
#     - node_modules
notifications:
  email:
    on_success: change
    on_failure: always
install:
  - yarn
jobs:
  include:
    - script:
        - yarn prettier --check
        # - yarn coverage
        # - yarn coveralls
        # - yarn build-all
after_success:
  - export SSHPASS=${SFTP_PASSWORD}
  - sshpass -e sftp -oBatchMode=no -b - ${SFTP_USER}@${SFTP_HOST}:poc << !
    pwd
    ls -la
    bye
    !
