# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: GitHub CI (v1.0.96)

on:
  workflow_dispatch:
    # inputs:
    #   tag:
    #     description: 'Tag'
    #     required: true
    #     default: 'canary'
  schedule:
    - cron: "0 */4 * * *"

env:
  tag: "1.0.96"

jobs:
  build:
    runs-on: ubuntu-latest
    # continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        framework:
          [
            angular,
            angularjs,
            aurelia,
            inferno,
            lit-element,
            preact,
            react,
            svelte,
            vanilla,
            vue,
            vue3,
          ]
    name: Test "${{matrix.framework}}" framework
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - name: Test "${{matrix.framework}}" framework
        shell: bash
        run: |
          cp -r public dist
          bash ./wake-up.sh ${{matrix.framework}} ${{env.tag}}
