# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: GitHub CI

on:
  push:
    branches:
      - development
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Build all framework variants
        run: |
          git status
          sh wake-up-all.sh
          git status
        working-directory: .github/workflows
      - name: List files
        run: ls -la dist
      - name: Git-Status
        run: git status
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: sftp://home292045786.1and1-data.host
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          known-hosts: ${{ secrets.FTP_KNOWN_HOSTS }}
          local-dir: dist/
