# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: GitHub CI (Webpack)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

env:
  tag: webpack

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Build all framework variants
        run: sh wake-up-all.sh ${{env.tag}}
      - name: List build artifacts
        run: |
          ls -la dist/
          mkdir ${{env.tag}}
          mv dist/* ${{env.tag}}/
          mv ${{env.tag}} dist/
          ls -la dist/${{env.tag}}/
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_HOST }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          known-hosts: ${{ secrets.FTP_KNOWN_HOSTS }}
          local-dir: dist/
          git-ftp-args: --all
